# Host list
# "name" is mandatory and will be used as target to connect
# "title" will be displayed as "human name" instead of "name" if specified
# All defaults values can be overriden per host basis
hosts:
  # 
  - name: figuren.theater
    title: figuren.theater
  # 
  - name: websites.fuer.figuren.theater
    title: websites.fuer.figuren.theater
  # 
  - name: mein.figuren.theater
    title: mein.figuren.theater
  # 
  - name: puppen.theater
    title: puppen.theater
  # 
  - name: assets.figuren.theater
    title: assets.figuren.theater

# Site configuration
site:
  # Title
  title: Status of figuren.theater WordPress multisite network
  # Favicon / logo
  favicon: https://figuren.theater/__media/2022/09/cropped-favicon-192x192.png
  # Refresh rate of status images for client
  refresh_rate_sec: 120

# Default values
defaults:
  # Default command to use
  # Supported values are :
  # - "curl"   [supports both uptime and response time, but only for HTTP/S requests]
  # - "ncat"   [supports both uptime and response time]
  # - "telnet" [supports only uptime]
  use: curl
  # Default timeout
  timeout: 30
  # Default port
  port: 443
  # Default number of ms before considering that host have latency problems
  status_slow_ms: 30000
